<div>
	<h3>
		Your lab is ready.
	</h3>

	<h4>
        <a href="/<?=$this->lab["code"];?>">
            <?=$this->lab_url;?><?=$this->lab["code"];?>
        </a>
	</h4>

	<p>
		Lab Name: <span class="name"><?=$this->lab["name"];?></span>
	</p>

	<p>
		<a class="share-lab" rel="<?=$this->lab_url;?><?=$this->lab["code"];?>" href="#">Share Via Email</a>
		<a class="copy-link" rel="<?=$this->lab_url;?><?=$this->lab["code"];?>" href="#">Copy Lab Link</a>
	</p>
</div>
